[project]
name = "mcp-lambda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "awslabs-aws-documentation-mcp-server>=0.1.4",
    "strands-agents>=0.1.4",
]
